// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class SplitLinerResources
{
        public const string achievement_quick_liner = "CgkIwpGH94kaEAIQAQ"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIwpGH94kaEAIQBg"; // <GPGSID>
        public const string achievement_re_liner = "CgkIwpGH94kaEAIQAw"; // <GPGSID>
        public const string achievement_high_liner = "CgkIwpGH94kaEAIQBA"; // <GPGSID>
        public const string achievement_sweet_liner = "CgkIwpGH94kaEAIQBQ"; // <GPGSID>
        public const string achievement_smooth_liner = "CgkIwpGH94kaEAIQAg"; // <GPGSID>

}

